// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvGQRmjTUC5vUOHkNFp-QMCbt4poEuVGM',
    appId: '1:248441550575:web:284e272d97054742aa0d1a',
    messagingSenderId: '248441550575',
    projectId: 'umlahelp-f1079',
    authDomain: 'umlahelp-f1079.firebaseapp.com',
    storageBucket: 'umlahelp-f1079.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrHIK01I8vqY1lsbrTFTbn3EJb_OVrpVI',
    appId: '1:248441550575:android:145f43fea367c9d8aa0d1a',
    messagingSenderId: '248441550575',
    projectId: 'umlahelp-f1079',
    storageBucket: 'umlahelp-f1079.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABVIWBUq1deaQPr68Bjk-O-gOqtQyCmJ0',
    appId: '1:248441550575:ios:a05e11fddc42a477aa0d1a',
    messagingSenderId: '248441550575',
    projectId: 'umlahelp-f1079',
    storageBucket: 'umlahelp-f1079.appspot.com',
    iosBundleId: 'com.example.umlaHelp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABVIWBUq1deaQPr68Bjk-O-gOqtQyCmJ0',
    appId: '1:248441550575:ios:a05e11fddc42a477aa0d1a',
    messagingSenderId: '248441550575',
    projectId: 'umlahelp-f1079',
    storageBucket: 'umlahelp-f1079.appspot.com',
    iosBundleId: 'com.example.umlaHelp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvGQRmjTUC5vUOHkNFp-QMCbt4poEuVGM',
    appId: '1:248441550575:web:9c3284c008e746abaa0d1a',
    messagingSenderId: '248441550575',
    projectId: 'umlahelp-f1079',
    authDomain: 'umlahelp-f1079.firebaseapp.com',
    storageBucket: 'umlahelp-f1079.appspot.com',
  );
}
